name       : openvswitch
version    : 2.12.0
release    : 2
source     :
    - https://github.com/openvswitch/ovs/archive/v2.12.0.tar.gz : 37b65fccd94e3757bb1c55e01416d4ce0e103cb52e33733fdd80a181e2a4fb68
license    : Apache-2.0
summary    : A multilayer software switch licensed under the open source Apache 2 license.
component  : network.util
description: |
    A multilayer software switch licensed under the open source Apache 2 license.
builddeps  :
    - pkgconfig(python3)
    - libcap-ng
    - python-six
    - unbound
rundeps    :
    - iproute2
    - libcap-ng
    - python3
    - python-six
    - unbound
setup      : |
    ./boot.sh
    %configure --enable-shared --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm0644 $pkgfiles/ovsdb-server.service $installdir/usr/lib/systemd/system/ovsdb-server.service
    install -Dm0644 $pkgfiles/ovs-vswitchd.service $installdir/usr/lib/systemd/system/ovs-vswitchd.service
    mkdir -p $installdir/usr/share/bash-completion/completions/
    mv $installdir/etc/bash_completion.d/ovs-vsctl-bashcomp.bash $installdir/usr/share/bash-completion/completions/ovs-vsctl-bashcomp
    mv $installdir/etc/bash_completion.d/ovs-appctl-bashcomp.bash $installdir/usr/share/bash-completion/completions/ovs-appctl-bashcomp
    rm -r $installdir/etc
